version: '3'

env:

  PROJECT_DIR: '.'
  CONTRACT_NAME: 'YourContract'

tasks:

  check:
    cmds:
      - solc --version
      - abigen --version
      - echo 'Environment ready!'

  build:
    dir: ./cmd/ethos
    cmds:
      - echo 'Build started'
      - go build
      - go install
      - echo 'Build finished'

  build-contracts:
    cmds:
      - echo 'Building contracts...'
      - solc --abi ./contracts/$CONTRACT_NAME.sol -o ./build --overwrite
      - solc --bin ./contracts/$CONTRACT_NAME.sol -o ./build --overwrite
      - abigen --bin=./build/$CONTRACT_NAME.bin --abi=./build/$CONTRACT_NAME.abi --pkg=main --out=./cmd/ethos/$CONTRACT_NAME.go
    silent: true
