version: '3'

tasks:

  check:
    cmds:
      - solc --version
      - abigen --version
      - echo 'Environment ready!'

  build:
    dir: ./cmd/ethos
    cmds:
      - echo 'Building...'
      - go build
      - go install
      - echo 'Done. `ethos` command is now available in $GOPATH/bin ('$GOPATH'/bin)'
    silent: true
