version: '3'

env:
  CONTRACT_DIR: '/home/drgomesp/src/scaffold-eth/packages/hardhat/contracts'
  CONTRACT_NAME: 'YourContract'

tasks:
  build-contracts:
    cmds:
      - echo 'Building contracts at '$CONTRACT_DIR
      - solc --abi $CONTRACT_DIR/$CONTRACT_NAME.sol -o ./build --overwrite
      - solc --bin $CONTRACT_DIR/$CONTRACT_NAME.sol -o ./build --overwrite
      - abigen --bin=./build/$CONTRACT_NAME.bin --abi=./build/$CONTRACT_NAME.abi --pkg=main --out=$CONTRACT_NAME.go
    silent: false

